export default [
  {
    id: 1,
    profilePic: "/profiles/Notcori.png",
    name: "Cheryl M",
    role: "Product Owner",
    linkedin: "https://www.linkedin.com/in/cheryl-h-murphy/",
    github: "https://github.com/cherylli",
    country: "/flag-australia.svg",
  },
  {
    id: 2,
    profilePic: "/profiles/ryo.jpg",
    name: "Ryo Izawa",
    role: "Frontend developer",
    linkedin: "https://www.linkedin.com/in/ryoizawa/",
    github: "https://www.linkedin.com/in/ryoizawa/",
    country: "/flag-japan.svg",
  },
  {
    id: 3,
    profilePic: "/profiles/emerson.jpg",
    name: "Emerson Bualat",
    role: "UI/UX Designer",
    linkedin: "#",
    github: "https://github.com/emerson-bualat",
    country: "/flag-philippines.svg",
  },
  {
    id: 4,
    profilePic: "/profiles/Dhia.jpg",
    name: "Dhia Prasetyo",
    role: "Product Designer",
    linkedin: "#",
    github: "https://github.com/dhiaprasetyo",
    country: "/flag-indonesia.svg",
  },
  {
    id: 5,
    profilePic: "/profiles/khemmie.jpg",
    name: "Khemmie Ray",
    role: "Frontend Developer",
    linkedin: "#",
    github: "https://github.com/dhiaprasetyo",
    country: "/flag-nigeria.svg",
  },
  {
    id: 6,
    profilePic: "/profiles/yuri.jpg",
    name: "Yuri Oda",
    role: "Frontend Developer",
    linkedin: "#",
    github: "https://github.com/YuriOda",
    country: "/flag-japan.svg",
    },
    {
      id: 7,
      profilePic: "/profiles/neko.jpeg",
      name: "@nekohack",
      role: "Frontend Developer", 
      linkedin: "#",
      github: "https://github.com/TKS9988",
      country: "/flag-japan.svg",
  },
];
